import React from 'react';
import TextField from '@material-ui/core/TextField';
import Autocomplete from '@material-ui/lab/Autocomplete';

export default function ComboBox() {
  return (
    <Autocomplete
      id="combo-box-demo"
      options={top100Films}
      getOptionLabel={(option) => option.title}
      style={{ width: 300,marginTop:'120px',marginLeft:'600px'}}
      renderInput={(params) => <TextField {...params} label="Enter Symptom" variant="outlined" />}
    />
  );
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const top100Films = [
  { title: 'shortness of breath', year: 1994 },
  { title: 'pain', year: 1972 },
  { title: 'fever', year: 1974 },
  { title: 'pain abdominal', year: 2008 },
  { title: 'diarrhea', year: 1957 },
  { title: "vomiting", year: 1993 },
  { title: 'asthenia', year: 1994 },
  { title: 'cough', year: 2003 },
  { title: 'dyspnea', year: 1966 },
  { title: 'nausea', year: 1999 },
  { title: 'unresponsiveness', year: 2001 },
  { title: 'chill', year: 1980 },
  { title: 'Forrest Gump', year: 1994 },
  { title: 'pain chest', year: 2010 },
  { title: 'apyrexial', year: 2002 },
  { title: "decreased body weight", year: 1975 },
  { title: 'agitation', year: 1990 },
  { title: 'rale', year: 1999 },
  { title: 'lesion', year: 1954 },
  { title: 'mass of body structure', year: 1977 },
  { title: 'hypotension', year: 2002 },
  { title: 'sore to touch', year: 1995 },
  { title: 'hallucinations auditory', year: 1991 },
  { title: "night sweat", year: 1946 },
  { title: 'orthopnea', year: 1997 },
  { title: 'syncope', year: 1995 },
  { title: 'thicken', year: 1994 },
  { title: 'haemorrhage', year: 2001 },
  { title: 'swelling', year: 1998 },
  { title: 'tremor', year: 1968 },
  { title: 'distress respiratory', year: 1998 },
  { title: 'feeling suicidal', year: 2014 },
  { title: 'hypokinesia', year: 1942 },
  { title: 'patient non compliance', year: 1931 },
  { title: 'suicidal', year: 1960 },
  { title: 'feeling hopeless', year: 1999 },
  { title: 'irritable mood', year: 2011 },
  { title: 'sleepy', year: 1936 },
  { title: 'sweating increased', year: 1981 },
  { title: 'tachypnea', year: 1954 },
  { title: 'wheezingt', year: 2002 },
  { title: 'worry', year: 2006 },
  { title: 'ascites', year: 1991 },
  { title: 'blackout', year: 1985 },
  { title: 'difficulty', year: 2014 },
  { title: 'dyspnea on exertion', year: 2000 },
  { title: 'headache', year: 2000 },
  { title: 'hemiplegia', year: 2006 },
  { title: 'hyponatremia', year: 1994 },
  { title: 'non-productive cough', year: 1979 },
  { title: 'pleuritic pain', year: 1979 },
  { title: 'pruritus', year: 1950 },
  { title: 'seizure	', year: 1964 },
  { title: 'sleeplessness', year: 1940 },
  { title: 'angina pectoris', year: 1988 },
  { title: 'constipation', year: 2006 },
  { title: 'facial paresis', year: 1988 },
  { title: 'fall', year: 1957 },
  { title: 'fatigue', year: 2012 },
  { title: 'hallucinations visual', year: 1980 },
  { title: 'hemodynamically stable', year: 2008 },
  { title: 'hyperkalemia', year: 1999 },
  { title: 'mental status changes', year: 2012 },
  { title: 'palpitation', year: 1997 },
  { title: 'productive cough', year: 1986 },
  { title: 'anorexia', year: 2003 },
  { title: 'bradycardia', year: 1984 },
  { title: 'chest tightness', year: 1957 },
  { title: 'dizziness', year: 1981 },
  { title: 'guaiac positive', year: 1941 },
  { title: 'homelessness', year: 1959 },
  { title: 'prostatism', year: 1958 },
  { title: 'tumor cell invasion', year: 1983 },
  { title: 'abdominal tenderness', year: 1992 },
  { title: 'abscess bacterial', year: 1995 },
  { title: 'chest discomfort', year: 1931 },
  { title: 'consciousness clear', year: 2000 },
  { title: 'decreased translucency', year: 2001 },
  { title: 'distended abdomen', year: 1971 },
  { title: 'erythema', year: 2007 },
  { title: 'jugular venous distention', year: 1976 },
  { title: 'lethargy', year: 1962 },
  { title: 'mood depressed', year: 1944 },
  { title: 'myalgia', year: 2004 },
  { title: 'redness', year: 1984 },
  { title: 'rhonchus', year: 1962 },
  { title: 'transaminitis', year: 2010 },
  { title: 'unconscious state', year: 2017 },
  { title: 'unsteady gait', year: 1987 },
  { title: 'weepiness', year: 2016 },
  { title: 'breath sounds decreased', year: 1973 },
  { title: 'dysarthria', year: 1968 },
  { title: "hematuria", year: 1952 },
  { title: 'intoxication', year: 1995 },
  { title: 'muscle twitch', year: 1948 },
  { title: 'nightmare', year: 1921 },
  { title: 'numbness', year: 2009 },
  { title: 'pressure chest', year: 2000 },
  { title: 'sinus rhythm', year: 2009 },
  { title: 'yellow sputum', year: 2009 },
  { title: 'verbal auditory hallucinations', year: 1975 },
];