import React from 'react';
import Checkbox from '@material-ui/core/Checkbox';
import FormGroup from '@material-ui/core/FormGroup';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import FormControl from '@material-ui/core/FormControl';
import FormLabel from '@material-ui/core/FormLabel';
import Button from '@material-ui/core/Button';
import Avatar from '@material-ui/core/Avatar';
import TextField from '@material-ui/core/TextField';
import LockOutlinedIcon from '@material-ui/icons/LockOutlined';
import Typography from '@material-ui/core/Typography';
import Container from '@material-ui/core/Container';
import Autocomplete from '@material-ui/lab/Autocomplete';
import {CheckStatus} from '../context/CheckStatus'

export default function ListOfSym({props}) {
  const [arr,setArr]=React.useState([])
  const [value, setValue] = React.useState();
  const user=React.useContext(CheckStatus)
  const displaySym = (props) => {
    
    if(props.e.target.checked)
        arr.push(props.sym)
        
    if(!props.e.target.checked)
      {let i=arr.indexOf(props.sym)
        arr.splice(i,i)
      }
      console.log(arr)
      user.setDataValues(arr)
    };
  const additionalSym = (p) => {
    alert("Added "+p.title)
    console.log(p.title)
    arr.push(p.title)
    console.log(arr)
    user.setDataValues(arr)
  };
  

    return (
      <div>
      <FormControl  component="fieldset">
        <FormGroup style={{padding:'20px'}} aria-label="position" row>
         {props.map((sym) =>(
          <FormControlLabel
            draggable
            value="end"
            control={<Checkbox color="primary"  />}
            label={sym}
            labelPlacement="end"
            onClick={(e => displaySym({e,sym}))}
            onDragEnd={(e => window.open("https://www.google.com/search?q="+sym, "_blank"))}
         />))} 
        </FormGroup>
      </FormControl>
        <Container style={{marginTop:'50px'}} component="main" maxWidth="xs">
        <Autocomplete
                    id="controllable-states-demo"
                    value={value}
                    onChange={(event, newValue) => {
                     setValue(newValue);
                             }}
                    options={top100Sym}
                    getOptionLabel={(option) => option.title}
                    // style={{ width: 300,marginTop:'120px',marginLeft:'600px'}}
                    renderInput={(params) => <TextField {...params} label="Enter Additional Symptom" variant="outlined" />}
    />
        <Button style={{marginTop:'25px'}} type="submit" fullWidth variant="contained" color="primary" onClick={(e=>additionalSym(value))}>+ ADD</Button>
          </Container>
      </div>
    );
  }
  const top100Sym = [
    { title: 'shortness of breath' },
    { title: 'pain' },
    { title: 'fever'},
    { title: 'pain abdominal'},
    { title: 'diarrhea'},
    { title: "vomiting" },
    { title: 'asthenia'},
    { title: 'cough' },
    { title: 'dyspnea'},
    { title: 'nausea'},
    { title: 'unresponsiveness' },
    { title: 'chill' },
    { title: 'pain chest'},
    { title: 'apyrexial' },
    { title: "decreased body weight" },
    { title: 'agitation'},
    { title: 'rale' },
    { title: 'lesion'},
    { title: 'mass of body structure'},
    { title: 'hypotension' },
    { title: 'sore to touch' },
    { title: 'hallucinations auditory'},
    { title: "night sweat" },
    { title: 'orthopnea' },
    { title: 'syncope'},
    { title: 'thicken'},
    { title: 'haemorrhage'},
    { title: 'swelling'},
    { title: 'tremor' },
    { title: 'distress respiratory'},
    { title: 'feeling suicidal' },
    { title: 'hypokinesia' },
    { title: 'patient non compliance' },
    { title: 'suicidal'},
    { title: 'feeling hopeless'},
    { title: 'irritable mood'},
    { title: 'sleepy'},
    { title: 'sweating increased'},
    { title: 'tachypnea'},
    { title: 'wheezingt' },
    { title: 'worry'},
    { title: 'ascites' },
    { title: 'blackout' },
    { title: 'difficulty' },
    { title: 'dyspnea on exertion' },
    { title: 'headache'},
    { title: 'hemiplegia' },
    { title: 'hyponatremia' },
    { title: 'non-productive cough' },
    { title: 'pleuritic pain'},
    { title: 'pruritus' },
    { title: 'seizure	'},
    { title: 'sleeplessness' },
    { title: 'angina pectoris' },
    { title: 'constipation' },
    { title: 'facial paresis'},
    { title: 'fall' },
    { title: 'fatigue'},
    { title: 'hallucinations visual'},
    { title: 'hemodynamically stable' },
    { title: 'hyperkalemia' },
    { title: 'mental status changes' },
    { title: 'palpitation'},
    { title: 'productive cough' },
    { title: 'anorexia' },
    { title: 'bradycardia' },
    { title: 'chest tightness' },
    { title: 'dizziness' },
    { title: 'guaiac positive' },
    { title: 'homelessness' },
    { title: 'prostatism' },
    { title: 'tumor cell invasion' },
    { title: 'abdominal tenderness' },
    { title: 'abscess bacterial' },
    { title: 'chest discomfort' },
    { title: 'consciousness clear'},
    { title: 'decreased translucency' },
    { title: 'distended abdomen' },
    { title: 'erythema' },
    { title: 'jugular venous distention'},
    { title: 'lethargy' },
    { title: 'mood depressed' },
    { title: 'myalgia' },
    { title: 'redness' },
    { title: 'rhonchus'},
    { title: 'transaminitis' },
    { title: 'unconscious state' },
    { title: 'unsteady gait' },
    { title: 'weepiness' },
    { title: 'breath sounds decreased'},
    { title: 'dysarthria'},
    { title: "hematuria"},
    { title: 'intoxication'},
    { title: 'muscle twitch'},
    { title: 'nightmare' },
    { title: 'numbness' },
    { title: 'pressure chest' },
    { title: 'sinus rhythm'},
    { title: 'yellow sputum'},
    { title: 'verbal auditory hallucinations'},
    {title:'catatonia'},
{title:'clonus'},
{title:'cushingoid habitus'},
{title:'ecchymosis'},
{title:'energy increased'},
{title:'extreme exhaustion'},
{title:'food intolerance'},
{title:'general discomfort'},
{title:'gurgle'},
{title:'haemoptysis'},
{title:'labored breathing'},
{title:'lightheadedness'},
{title:'metastatic lesion'},
{title:'motor retardation'},
{title:'oliguria'},
{title:'orthostasis'},
{title:'scar tissue'},
{title:'snuffle'},
{title:'speech slurred'},
{title:'splenomegaly'},
{title:'throat sore'},
{title:'vertigo'},
{title:'asterixis'},
{title:'aura'},
{title:'bedridden'},
{title:'burning sensation'},
{title:'cachexia'},
{title:'drowsiness'},
{title:'dysuria'},
{title:'egophony'},
{title:'enuresis'},
{title:'fremitus'},
{title:'gravida 0'},
{title:'green sputum'},
{title:'has religious belief'},
{title:'heartburn'},
{title:'hypothermia, natural'},
{title:'hypoxemia'},
{title:'left atrial hypertrophy'},
{title:'lung nodule'},
{title:'nausea and vomiting'},
{title:'neck stiffness'},
{title:'nervousness'},
{title:'numbness of hand'},
{title:'painful swallowing'},
{title:'paresthesia'},
{title:'polydypsia'},
{title:'polyuria'},
{title:'sensory discomfort'},
{title:'spontaneous rupture of membranes'},
{title:'stiffness'},
{title:'symptom aggravating factors'},
{title:'urge incontinence'},
{title:'urgency of micturition'},
{title:'weight gain'},
{title:'withdraw'},
{title:'achalasia'},
{title:'arthralgia'},
{title:'ataxia'},
{title:'breech presentation'},
{title:'cardiomegaly'},
{title:'cardiovascular event'},
{title:'colic abdominal'},
{title:'cyanosis'},
{title:'debilitation'},
{title:'decompensation'},
{title:'difficulty passing urine'},
{title:'emphysematous change'},
{title:'fatigability'},
{title:'flatulence'},
{title:'formication'},
{title:'frail'},
{title:'hematocrit decreased'},
{title:'heme positive'},
{title:'hepatosplenomegaly'},
{title:'hoarseness'},
{title:'hypercapnia'},
{title:'indifferent mood'},
{title:'loose associations'},
{title:'malaise'},
{title:'moan'},
{title:'monoclonal'},
{title:'neologism'},
{title:'out of breath'},
{title:'paraparesis'},
{title:'paresis'},
{title:'photophobia'},
{title:'polymyalgia'},
{title:'presence of q wave'},
{title:'projectile vomiting'},
{title:'qt interval prolonged'},
{title:'room spinning'},
{title:'satiety early'},
{title:'scratch marks'},
{title:'snore'},
{title:'spasm'},
{title:'stahlis line'},
{title:'stool color yellow'},
{title:'stupor'},
{title:'systolic murmur'},
{title:'t wave inverted'},
{title:'tenesmus'},
{title:'terrify'},
{title:'tired'},
{title:'unhappy'},
{title:'urinary hesitation'},
{title:'verbally abusive behavior'},
{title:'wheelchair bound'},
{title:'abnormally hard consistency'},
{title:'absences finding'},
{title:'ache'},
{title:'ambidexterity'},
{title:'aphagia'},
{title:'asymptomatic'},
{title:'atypia'},
{title:'awakening early'},
{title:'behavior hyperactive'},
{title:'bleeding of vagina'},
{title:'cicatrisation'},
{title:'clammy skin'},
{title:'cystic lesion'},
{title:'decreased stool caliber'},
{title:'disturbed family'},
{title:'dullness'},
{title:'estrogen use'},
{title:'extrapyramidal sign'},
{title:'feeling strange'},
{title:'flushing'},
{title:'general unsteadiness'},
{title:'giddy mood'},
{title:'groggy'},
{title:'hacking cough'},
{title:'heavy legs'},
{title:'hemianopsia homonymous'},
{title:'hepatomegaly'},
{title:'hirsutism'},
{title:'hot flush'},
{title:'hunger'},
{title:'hydropneumothorax'},
{title:'hyperacusis'},
{title:'hypersomnia'},
{title:'hypoalbuminemia'},
{title:'hypocalcemia result'},
{title:'hypokalemia'},
{title:'hypotonic'},
{title:'impaired cognition'},
{title:'lip smacking'},
{title:'mass in breast'},
{title:'mediastinal shift'},
{title:'moody'},
{title:'myoclonus'},
{title:'nonsmoker'},
{title:'pain back'},
{title:'pallor'},
{title:'para 1'},
{title:'paralyse'},
{title:'poor dentition'},
{title:'posturing'},
{title:'pulsus paradoxus'},
{title:'pustule'},
{title:'renal angle tenderness'},
{title:'scleral icterus'},
{title:'side pain'},
{title:'slowing of urinary stream'},
{title:'sputum purulent'},
{title:'st segment depression'},
{title:'stridor'},
{title:'stuffy nose'},
{title:'superimposition'},
{title:'systolic ejection murmur'},
{title:'unable to concentrate'},
{title:'uncoordination'},
{title:'vision blurred'},
{title:'abdomen acute'},
{title:'abdominal bloating'},
{title:'abnormal sensation'},
{title:'abortion'},
{title:'adverse effect'},
{title:'air fluid level'},
{title:'alcohol binge episode'},
{title:'alcoholic withdrawal symptoms'},
{title:'anosmia'},
{title:'barking cough'},
{title:'behavior showing increased motor activity'},
{title:'blanch'},
{title:'bowel sounds decreased'},
{title:'bradykinesia'},
{title:'breakthrough pain'},
{title:'breath-holding spell'},
{title:'bruit'},
{title:'catching breath'},
{title:'charleyhorse'},
{title:'choke'},
{title:'claudication'},
{title:'clumsiness'},
{title:'coordination abnormal'},
{title:'disequilibrium'},
{title:'dizzy spells'},
{title:'drool'},
{title:'dysdiadochokinesia'},
{title:'dysesthesia'},
{title:'dyspareunia'},
{title:'elation'},
{title:'excruciating pain'},
{title:'exhaustion'},
{title:'fear of falling'},
{title:'fecaluria'},
{title:'feces in rectum'},
{title:'feels hot feverish'},
{title:'flare'},
{title:'floppy'},
{title:'focal seizures'},
{title:'frothy sputum'},
{title:'gag'},
{title:'gasping for breath'},
{title:'gravida 10'},
{title:'heavy feeling'},
{title:'heberdens node'},
{title:'hematochezia'},
{title:'history of - blackout'},
{title:'hoard'},
{title:'homicidal thoughts'},
{title:'hyperemesis'},
{title:'hyperhidrosis disorder'},
{title:'hypersomnolence'},
{title:'hypertonicity'},
{title:'hyperventilation'},
{title:'hypesthesia'},
{title:'hypometabolism'},
{title:'hypoproteinemia'},
{title:'immobile'},
{title:'inappropriate affect'},
{title:'incoherent'},
{title:'intermenstrual heavy bleeding'},
{title:'large-for-dates fetus'},
{title:'low back pain'},
{title:'macerated skin'},
{title:'macule'},
{title:'milky'},
{title:'monocytosis'},
{title:'murphys sign'},
{title:'mydriasis'},
{title:'nasal discharge present'},
{title:'nasal flaring'},
{title:'no known drug allergies'},
{title:'no status change'},
{title:'noisy respiration'},
{title:'overweight'},
{title:'pain foot'},
{title:'pain in lower limb'},
{title:'pain neck'},
{title:'panic'},
{title:'pansystolic murmur'},
{title:'para 2'},
{title:'passed stones'},
{title:'pericardial friction rub'},
{title:'phonophobia'},
{title:'photopsia'},
{title:'pin-point pupils'},
{title:'pneumatouria'},
{title:'poor feeding'},
{title:'posterior rhinorrhea'},
{title:'previous pregnancies '},
{title:'primigravida'},
{title:'prodrome'},
{title:'prostate tender'},
{title:'proteinemia'},
{title:'pulse absent'},
{title:'r wave feature'},
{title:'rambling speech'},
{title:'rapid shallow breathing'},
{title:'red blotches'},
{title:'regurgitates after swallowing'},
{title:'rest pain'},
{title:'retch'},
{title:'retropulsion'},
{title:'rhd positive'},
{title:'rigor - temperature-associated observation'},
{title:'rolling of eyes'},
{title:'sciatica'},
{title:'sedentary'},
{title:'shooting pain'},
{title:'sneeze'},
{title:'sniffle'},
{title:'soft tissue swelling'},
{title:'st segment elevation'},
{title:'stinging sensation'},
{title:'throbbing sensation quality'},
{title:'tinnitus'},
{title:'titubation'},
{title:'todd paralysis'},
{title:'tonic seizures'},
{title:'transsexual'},
{title:'tremor resting'},
{title:'underweight'},
{title:'unwell'},
{title:'urinoma'},
{title:'welt'},
  ];
  